### PR TITLE
Change Cake Aliases to be more consistent

### PR DESCRIPTION
**Pull request by patriksvensson**
Changing the alias will make it easier to discover at the
http://cakebuild.net site.

### CODE REVIEW

**Comment by gep13** [comment]
Thank you very much! :+1:

**Comment by patriksvensson** [comment]
Is this up on NuGet yet?

**Comment by gep13** [comment]
No, not yet. I have some pending changes to the underlying ReSharperReports tool, so wasn't going to be pushing this Cake Addin until I do that.

**Comment by gep13** [comment]
It "would" be on my MyGet feed, but I haven't pulled in GitVersion yet into this build pipeline to provide unique version numbers, so only the 0.1.0 is available on my MyGet feed.

**Comment by patriksvensson** [comment]
Ah, ok. Tell me when it's on NuGet :smile:

**Comment by gep13** [comment]
Will do.

**Comment by gep13** [comment]
@patriksvensson this is now on NuGet, so should be good to pull in my request to get website updated.

**Pull request merged**
